language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.14.0

install:
  - git clone https://github.com/bitcoin/secp256k1.git
  - cd secp256k1
  - ./autogen.sh && ./configure && make && sudo make install
  - sudo ldconfig /usr/local/lib

