[package]
name = "schemars"
version = "0.1.0"
authors = ["Jeremy Rubin <j@rubin.io>"]
edition = "2018"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[dependencies.bitcoin_hashes]
path = "../.."
features = ['schemars', 'serde']

[dependencies]
jsonschema-valid = "^0.4.0"
serde = { version = "1.0", default-features = false}
schemars = { version = "<=0.8.3"}
serde_test = "1.0"
serde_json = "1.0"
