name: Manage PR
on:
  - pull_request_target # zizmor: ignore[dangerous-triggers]
permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout master
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: master
          persist-credentials: false
      - name: Checkout merge commit
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: merge
          ref: "refs/pull/${{ github.event.number }}/merge"
          persist-credentials: false
      - name: Generate label config
        run: cd master && SCAN_DIR=../merge ./contrib/gen_label_config.sh
      - name: Update labels
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          configuration-path: master/.github/labeler.yml
          sync-labels: true
